import {test} from 'node:test';
import assert from 'node:assert/strict';
import {prepareCompaction,compactionView,thresholdTokens} from './hermes-compaction.mjs';
import {runHermesTurn} from './hermes-loop.mjs';
const canonical=[{role:'system',content:'policy'},{role:'user',content:'old request'},{role:'assistant',content:'',tool_calls:[{id:'a',function:{name:'read',arguments:'{}'}}]},{role:'tool',tool_call_id:'a',content:'evidence'},{role:'assistant',content:'finished'},{role:'user',content:'current request'}];
function fixture(){let summaries=0;const checkpoints=[];return {checkpoints,get summaries(){return summaries;},measure:async(messages,tools,reserve)=>({promptTokens:messages[0]?.content?.startsWith('Summarize')?1000:messages.some(m=>m.content?.startsWith('[CONTEXT COMPACTION'))?600:2800,contextTokens:4096,reservedOutputTokens:reserve}),summarize:async()=>{summaries++;return {content:'Completed old request with evidence.',finish_reason:'stop'};},checkpoint:async(messages,state)=>checkpoints.push(structuredClone({messages,state})),model:async()=>({content:'Answer',finish_reason:'stop'}),execute:async()=>{throw Error('must not replay');}};}
test('threshold reserves output and applies pinned upstream small-window floor cap',()=>{assert.equal(thresholdTokens(4096,1024),2611);assert.equal(thresholdTokens(128000,8192),64000);assert.equal(thresholdTokens(4096,1024,1),2611);});
test('compact view preserves canonical history and entire tool batch in summarized prefix',async()=>{const host=fixture(),before=structuredClone(canonical);const result=await prepareCompaction(canonical,[],undefined,host);assert.deepEqual(canonical,before);assert.equal(result.state.coveredCount,5);assert.equal(result.state.prefixJSON,JSON.stringify(canonical.slice(0,5)));assert.deepEqual(result.messages.at(-1),canonical.at(-1));assert.equal(result.messages[0].content,'policy');assert.equal(host.summaries,1);const repeat=await prepareCompaction(canonical,[],result.state,host);assert.deepEqual(repeat,result);assert.equal(host.summaries,1);});
test('oversized pending tool batch, current-only exchange and altered prefix refuse compaction',async()=>{const host=fixture();host.measure=async(m,t,r)=>({promptTokens:m[0]?.content?.startsWith('Summarize')?1000:m.some(x=>x.content?.startsWith('[CONTEXT COMPACTION'))?600:3500,contextTokens:4096,reservedOutputTokens:r});await assert.rejects(prepareCompaction(canonical.slice(0,4),[],undefined,host),/cannot be compacted/);await assert.rejects(prepareCompaction(canonical.slice(0,2),[],undefined,host),/cannot be compacted/);const result=await prepareCompaction(canonical,[],undefined,host);assert.throws(()=>compactionView([{...canonical[0],content:'different'},...canonical.slice(1)],result.state),/Invalid compaction/);});
test('summary refusal/truncation/tool use/oversize input fail without mutating transcript',async()=>{for(const reply of [{content:'partial',finish_reason:'length'},{content:'',finish_reason:'stop'},{content:'I cannot summarize this',finish_reason:'stop'},{content:'text',finish_reason:'stop',tool_calls:[{}]}]){const host=fixture();host.summarize=async()=>reply;await assert.rejects(prepareCompaction(canonical,[],undefined,host),/Incomplete or refused/);}const host=fixture();host.measure=async(m,t,r)=>({promptTokens:5000,contextTokens:4096,reservedOutputTokens:r});await assert.rejects(prepareCompaction(canonical,[],undefined,host),/Summary input exceeds/);});
test('failed compaction checkpoint blocks next model and preserves previous durable transcript',async()=>{const host=fixture();let calls=0;host.model=async()=>{calls++;return {content:'wrong'};};host.checkpoint=async(m,s)=>{assert.deepEqual(m,canonical);if(s.compaction)throw Error('disk full');};await assert.rejects(runHermesTurn({messages:canonical,compaction:true},host),/disk full/);assert.equal(calls,0);});
test('resume reuses compacted inference view while final transcript stays lossless and tools never replay',async()=>{const host=fixture(),prepared=await prepareCompaction(canonical,[],undefined,host);let received;host.model=async m=>{received=m;return {content:'Answer',finish_reason:'stop'};};const result=await runHermesTurn({compaction:true,resume:{messages:canonical,state:{compaction:prepared.state}}},host);assert.deepEqual(received,prepared.messages);assert.deepEqual(result.messages.slice(0,-1),canonical);assert.equal(host.summaries,1);assert.ok(host.checkpoints.every(c=>c.messages[2].tool_calls[0].id==='a'));});
test('cancellation after summary rejects without publishing state',async()=>{const host=fixture(),controller=new AbortController();host.signal=controller.signal;host.summarize=async()=>{controller.abort();return {content:'summary',finish_reason:'stop'};};await assert.rejects(prepareCompaction(canonical,[],undefined,host),/cancelled/);assert.equal(host.checkpoints.length,0);});
test('threshold exactly matches executed pinned upstream extracted helpers',async()=>{
 const {execFileSync}=await import('node:child_process');
 const cases=[[4096,1024,.5],[8192,1024,.5],[64000,4096,.5],[128000,8192,.5],[1000000,8192,.5],[4096,1024,1],[4096,1024,.9]];
 const script='import runpy,json,sys\nc=runpy.run_path(sys.argv[1])["ContextCompressor"]\nprint(json.dumps([c._compute_threshold_tokens(ctx,pct,reserve) for ctx,reserve,pct in json.loads(sys.argv[2])]))';
 const path=new URL('./compaction-threshold-upstream.py',import.meta.url).pathname;
 assert.deepEqual(cases.map(([ctx,reserve,pct])=>thresholdTokens(ctx,reserve,pct)),JSON.parse(execFileSync('python3',['-c',script,path,JSON.stringify(cases)],{encoding:'utf8'})));
});
test('new summary must actually shrink the measured model context',async()=>{const host=fixture();host.measure=async(m,t,r)=>({promptTokens:m[0]?.content?.startsWith('Summarize')?1000:2800,contextTokens:4096,reservedOutputTokens:r});await assert.rejects(prepareCompaction(canonical,[],undefined,host),/did not produce/);});

test('high but fitting active exchange passes intact without a summary',async()=>{const host=fixture(),messages=canonical.slice(0,2);const result=await prepareCompaction(messages,[],undefined,host);assert.deepEqual(result,{messages,state:undefined});assert.equal(host.summaries,0);});
test('reused summary with no new complete exchange passes when high but still fitting',async()=>{const host=fixture(),first=await prepareCompaction(canonical,[],undefined,host);host.measure=async(m,t,r)=>({promptTokens:2800,contextTokens:4096,reservedOutputTokens:r});const result=await prepareCompaction(canonical,[],first.state,host);assert.deepEqual(result,first);assert.equal(host.summaries,1);});
test('oversized summary input defers compaction only when existing view fits hard budget',async()=>{const host=fixture();host.measure=async(m,t,r)=>({promptTokens:m[0]?.content?.startsWith('Summarize')?5000:2800,contextTokens:4096,reservedOutputTokens:r});const result=await prepareCompaction(canonical,[],undefined,host);assert.deepEqual(result,{messages:canonical,state:undefined});assert.equal(host.summaries,0);});
