// Generated by node --import tsx scripts/sync-expanded-provider-metadata.ts.
export const EXPANDED_PROVIDER_ACCESS = {
  "fireworks": {
    "paid": true,
    "free": false,
    "note": "Usage is metered; limited promotional credit is a trial, not a free tier.",
    "source": "https://fireworks.ai/pricing"
  },
  "deepinfra": {
    "paid": true,
    "free": false,
    "note": "Pay-as-you-go service; promotional or trial credit is not a free tier.",
    "source": "https://deepinfra.com/pricing"
  },
  "nebius": {
    "paid": true,
    "free": false,
    "note": "Metered inference; account or regional trial credit is not a free tier.",
    "source": "https://studio.nebius.com/pricing"
  },
  "sambanova": {
    "paid": true,
    "free": true,
    "note": "Free and paid cloud plans have separate, model-specific rate limits.",
    "source": "https://cloud.sambanova.ai/plans/pricing"
  },
  "siliconflow": {
    "paid": true,
    "free": true,
    "note": "The catalog includes paid and explicitly marked free models; limits vary by model.",
    "source": "https://cloud.siliconflow.com/models"
  },
  "novita": {
    "paid": true,
    "free": false,
    "note": "Usage is credit-metered; account-specific signup credit is a trial, not a free tier.",
    "source": "https://novita.ai/pricing"
  },
  "nvidia-nim": {
    "paid": true,
    "free": false,
    "note": "The hosted build API offers evaluation access; evaluation access is not a free production tier.",
    "source": "https://build.nvidia.com/explore/discover"
  },
  "codestral": {
    "paid": true,
    "free": false,
    "note": "Codestral is metered; experimental access is excluded from free-tier availability.",
    "source": "https://mistral.ai/pricing"
  },
  "cohere": {
    "paid": true,
    "free": false,
    "note": "Trial keys are rate-limited and restricted; production keys use paid billing.",
    "source": "https://docs.cohere.com/docs/rate-limits"
  },
  "ai21": {
    "paid": true,
    "free": false,
    "note": "Metered API access; account-specific trial credit is not a free tier.",
    "source": "https://www.ai21.com/pricing"
  },
  "chutes": {
    "paid": true,
    "free": false,
    "note": "Subscription and pay-as-you-go are separate; this integration reads subscription windows when present.",
    "source": "https://chutes.ai/pricing"
  },
  "venice": {
    "paid": true,
    "free": true,
    "note": "API inference can consume DIEM or USD; a balance is not a subscription quota.",
    "source": "https://docs.venice.ai/api-reference/endpoint/billing/get_balance"
  },
  "kilo": {
    "paid": true,
    "free": true,
    "note": "Kilo Pass allowance is separate from gateway pay-as-you-go credits; Auto Free is also available.",
    "source": "https://kilo.ai/docs/code-with-ai/agents/kilo-pass"
  },
  "byteplus-coding": {
    "paid": true,
    "free": false,
    "note": "Coding Plan subscription; ordinary ModelArk pay-as-you-go balances are outside this quota surface.",
    "source": "https://docs.byteplus.com/en/docs/ModelArk/1976647"
  },
  "xiaomi-token-plan": {
    "paid": true,
    "free": false,
    "note": "Token Plan subscription; ordinary API billing is distinct.",
    "source": "https://platform.xiaomimimo.com/#/docs/pricing"
  },
  "xiaomi-token-plan-ams": {
    "paid": true,
    "free": false,
    "note": "European Token Plan subscription; ordinary API billing is distinct.",
    "source": "https://platform.xiaomimimo.com/#/docs/pricing"
  },
  "xiaomi-token-plan-sgp": {
    "paid": true,
    "free": false,
    "note": "Singapore Token Plan subscription; ordinary API billing is distinct.",
    "source": "https://platform.xiaomimimo.com/#/docs/pricing"
  },
  "ollama-cloud": {
    "paid": true,
    "free": true,
    "note": "Cloud plans include monthly usage; API keys do not expose the plan meter.",
    "source": "https://ollama.com/pricing"
  },
  "synthetic": {
    "paid": true,
    "free": false,
    "note": "Subscription quota lanes are returned by the quota API.",
    "source": "https://dev.synthetic.new/docs/synthetic/quotas"
  },
  "orcarouter": {
    "paid": true,
    "free": true,
    "note": "API-key billing; the documented orcarouter/free route has a bounded free tier.",
    "source": "https://docs.orcarouter.ai/routing/free-models"
  },
  "martian": {
    "paid": true,
    "free": false,
    "note": "Gateway API key; public docs do not promise a free inference allowance.",
    "source": "https://docs.withmartian.com/quickstart"
  },
  "crofai": {
    "paid": true,
    "free": false,
    "note": "Pay-per-token API; account creation requires no card, but the site does not promise free inference credit.",
    "source": "https://crof.ai"
  },
  "inceptron": {
    "paid": true,
    "free": false,
    "note": "API-key inference; published pricing is pay as you go.",
    "source": "https://www.inceptron.io/pricing"
  },
  "neuralwatt": {
    "paid": true,
    "free": false,
    "note": "API-key inference; no documented recurring free allowance or key-readable balance.",
    "source": "https://portal.neuralwatt.com/docs"
  },
  "baseten": {
    "paid": true,
    "free": false,
    "note": "Model APIs are usage billed; limits and usage are managed in the Baseten workspace.",
    "source": "https://docs.baseten.co/inference/model-apis/pricing-and-limits"
  },
  "replicate": {
    "paid": true,
    "free": false,
    "note": "Pay-as-you-go prediction jobs; there is no documented generic chat-completions contract.",
    "source": "https://replicate.com/docs/topics/billing/index"
  },
  "fal": {
    "paid": true,
    "free": false,
    "note": "Usage-billed fal endpoint backed by OpenRouter; no documented key-readable allowance.",
    "source": "https://fal.ai/docs/model-api-reference/vision-api/openrouter-router"
  },
  "bedrock": {
    "paid": true,
    "free": false,
    "note": "Use an Amazon Bedrock API key and your region's OpenAI-compatible endpoint. AWS IAM access keys are not accepted in this field. Quotas are managed in AWS.",
    "source": "https://docs.aws.amazon.com/bedrock/latest/userguide/bedrock-mantle.html"
  },
  "azure-foundry": {
    "paid": true,
    "free": false,
    "note": "Enter your Foundry resource endpoint and deployed model names. Uses the v1 cross-provider API; Azure billing and resource quotas stay in the Azure portal.",
    "source": "https://learn.microsoft.com/en-us/azure/ai-foundry/foundry-models/how-to/use-chat-completions"
  },
  "vertex-express": {
    "paid": true,
    "free": false,
    "note": "Use a Vertex AI Express mode key. Trials are time limited; billing is pay-as-you-go. Standard project/service-account credentials are not Express keys.",
    "source": "https://cloud.google.com/vertex-ai/generative-ai/docs/start/express-mode/overview"
  },
  "cloudflare": {
    "paid": true,
    "free": true,
    "note": "Use an API token with Workers AI permission and an endpoint containing your Cloudflare account ID. Daily compute allowances are managed in Cloudflare.",
    "source": "https://developers.cloudflare.com/workers-ai/platform/pricing/"
  }
};
export const SDK_PROVIDER_NAMES: Record<string, string> = {
  "bedrock": "AWS Bedrock",
  "azure-foundry": "Azure AI Foundry",
  "vertex-express": "Google Vertex AI (Express)",
  "cloudflare": "Cloudflare Workers AI",
  "fireworks": "Fireworks AI",
  "deepinfra": "DeepInfra",
  "nebius": "Nebius AI Studio",
  "sambanova": "SambaNova Cloud",
  "siliconflow": "SiliconFlow",
  "novita": "Novita AI",
  "nvidia-nim": "NVIDIA NIM",
  "codestral": "Mistral Codestral",
  "cohere": "Cohere",
  "ai21": "AI21 Labs",
  "chutes": "Chutes.ai",
  "venice": "Venice AI",
  "kilo": "Kilo AI Gateway",
  "byteplus-coding": "BytePlus Coding Plan",
  "xiaomi-token-plan": "Xiaomi MiMo Token Plan (China)",
  "xiaomi-token-plan-ams": "Xiaomi MiMo Token Plan (Europe)",
  "xiaomi-token-plan-sgp": "Xiaomi MiMo Token Plan (Singapore)",
  "ollama-cloud": "Ollama Cloud",
  "synthetic": "Synthetic",
  "orcarouter": "OrcaRouter",
  "martian": "Martian",
  "crofai": "CrofAI",
  "inceptron": "Inceptron",
  "neuralwatt": "Neuralwatt",
  "baseten": "Baseten",
  "replicate": "Replicate",
  "fal": "fal.ai",
  "poe": "Poe",
  "minimax": "MiniMax",
  "minimax-coding": "MiniMax Token Plan",
  "kimi": "Kimi",
  "kimi-coding": "Kimi Code",
  "huggingface": "Hugging Face",
  "abacus": "Abacus.AI",
  "qwen-coding": "Qwen Coding Plan (Alibaba)",
  "manus": "Manus",
  "anthropic": "Anthropic",
  "google": "Google Gemini",
  "mammouth": "Mammouth AI",
  "openrouter": "OpenRouter",
  "deepseek": "DeepSeek",
  "groq": "Groq",
  "togetherai": "Together AI",
  "cerebras": "Cerebras",
  "perplexity": "Perplexity"
};
