#!/usr/bin/env node
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateContainerReleaseMetadata } from '../provider-host/provider-host-container-release.mjs';

export function checksums(text) {
  const result = new Map();
  for (const line of text.trim().split(/\r?\n/u)) {
    const match = /^([a-f0-9]{64})  ([A-Za-z0-9._-]+)$/u.exec(line);
    if (!match || result.has(match[2])) throw new Error('Invalid or duplicate checksum record');
    result.set(match[2], match[1]);
  }
  return result;
}
export function releaseInputs(metadata, sums) {
  validateContainerReleaseMetadata(metadata, metadata.version, metadata.sourceCommit);
  if (!/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/u.test(metadata.version)) throw new Error('Distribution packages require a stable version');
  const hashes = checksums(sums);
  for (const arch of ['arm64', 'amd64']) {
    if (!hashes.has(`multivibe-host_${metadata.version}_darwin_${arch}.dmg`)) throw new Error(`Missing ${arch} DMG checksum`);
  }
  return hashes;
}
export function homebrew(metadata, hashes) {
  const version = metadata.version;
  return `# Generated by scripts/distribution/generate.mjs from release SHA256SUMS.
cask "multivibe-host" do
  arch arm: "arm64", intel: "amd64"

  version "${version}"
  sha256 arm:   "${hashes.get(`multivibe-host_${version}_darwin_arm64.dmg`)}",
         intel: "${hashes.get(`multivibe-host_${version}_darwin_amd64.dmg`)}"

  url "https://github.com/thibautrey/multivibe/releases/download/v#{version}/multivibe-host_#{version}_darwin_#{arch}.dmg"
  name "MultiVibe Host"
  desc "Local AI model host with a native menu bar and opt-in provider sharing"
  homepage "https://github.com/thibautrey/multivibe"

  auto_updates true
  app "MultiVibe Host.app"

  uninstall launchctl: ["cloud.multivibe.host", "cloud.multivibe.host.update"],
            quit:      "cloud.multivibe.host"

  caveats <<~EOS
    Launch MultiVibe Host from Applications to finish setup.
    Its built-in signed updater is enabled by default.
    Uninstall preserves application data and downloaded models.
  EOS
end
`;
}
export function service(image) {
  return {
    image, platform: 'linux/amd64', init: true, restart: 'unless-stopped',
    read_only: true, tmpfs: ['/tmp:rw,nosuid,nodev,noexec,mode=1777,size=512m'],
    security_opt: ['no-new-privileges:true'], cap_drop: ['ALL'],
    cap_add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID'], stop_grace_period: '45s',
    environment: {
      MULTIVIBE_HOST_PUBLIC_URL: '${MULTIVIBE_HOST_PUBLIC_URL:?Set the exact browser-facing origin}',
      MULTIVIBE_HOST_MANAGED_DIR: '/models/runtime',
      MULTIVIBE_PROVIDER_CUDA_VISIBLE_DEVICES: '0',
      NVIDIA_DRIVER_CAPABILITIES: 'compute,utility',
    },
    ports: ['${MULTIVIBE_HOST_PORT:-1455}:1455'],
    volumes: ['${MULTIVIBE_DATA_DIR:?Select a dedicated appdata directory}:/data', '${MULTIVIBE_MODELS_DIR:?Select a dedicated models directory}:/models'],
    deploy: { resources: { reservations: { devices: [{ driver: 'nvidia', device_ids: ['${NVIDIA_GPU_UUID:?Select an NVIDIA GPU UUID}'], capabilities: ['gpu'] }] } } },
  };
}
export async function generate(metadata, sums, output) {
  const hashes = releaseInputs(metadata, sums);
  const files = new Map();
  files.set('homebrew/Casks/multivibe-host.rb', homebrew(metadata, hashes));
  const compose = { name: 'multivibe-host', services: { 'multivibe-host': service(`${metadata.versionTag}@${metadata.digest}`) } };
  const icon = 'https://raw.githubusercontent.com/thibautrey/multivibe/main/assets/brand/favicon/favicon-256x256.png';
  const casa = structuredClone(compose);
  // CasaOS/ZimaOS supplies its persistent data root. Public URL and GPU selection
  // remain explicit inputs; never derive an origin from an internal container IP.
  const casaHost = casa.services['multivibe-host'];
  casaHost.volumes = ['/DATA/AppData/multivibe-host/data:/data', '/DATA/AppData/multivibe-host/models:/models'];
  casaHost.environment.MULTIVIBE_HOST_PUBLIC_URL = '';
  casaHost.environment.NVIDIA_VISIBLE_DEVICES = 'all';
  casaHost.runtime = 'nvidia';
  casaHost.ports = ['1455:1455'];
  delete casaHost.deploy;
  casa['x-casaos'] = {
    id: 'cloud.multivibe.host', architectures: ['amd64'], main: 'multivibe-host',
    category: 'AI', developer: 'MultiVibe', author: 'MultiVibe',
    title: { en_US: 'MultiVibe Host' }, tagline: { en_US: 'Run local AI models on your NVIDIA GPU' },
    description: { en_US: 'Beta. Requires x86_64 and an NVIDIA GPU with compute capability 7.0+. In app settings, set MULTIVIBE_HOST_PUBLIC_URL to the exact browser origin (for example http://192.168.1.10:1455) before starting. Set NVIDIA_VISIBLE_DEVICES to a GPU UUID to select one GPU. Configure local capacity with /models/weights. Model downloads and provider sharing are opt-in. Application state and models survive container replacement.' },
    icon, scheme: 'http', index: '/', port_map: '1455', version: metadata.version,
    website: 'https://github.com/thibautrey/multivibe',
  };
  files.set('casaos/Apps/MultiVibeHost/docker-compose.yml', JSON.stringify(casa, null, 2) + '\n');
  files.set('truenas/docker-compose.custom.yml', JSON.stringify(compose, null, 2) + '\n');
  files.set('truenas/multivibe-host/ix_values.yaml', JSON.stringify({images:{image:{repository:metadata.image,tag:`${metadata.version}@${metadata.digest}`}},consts:{host_container_name:'multivibe-host'}}, null, 2)+'\n');
  const app = {
    annotations: { min_scale_version: '24.10.2.2' }, app_version: metadata.version,
    capabilities: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID'].map(name => ({name, description: 'Prepare dedicated storage and drop to UID/GID 10001 at startup'})),
    categories: ['ai'], changelog_url: 'https://github.com/thibautrey/multivibe/releases',
    date_added: '2026-09-07', description: 'Local AI model Host for x86_64 NVIDIA GPUs (compute capability 7.0+). Sharing and model downloads are opt-in.',
    home: 'https://github.com/thibautrey/multivibe', host_mounts: [], icon, keywords: ['ai', 'llm', 'nvidia'],
    lib_version: '2.3.11', lib_version_hash: '874636814efb275e5276ea9d709b7cd665fed42bb1d50328e853d9253a2e1229',
    maintainers: [{name: 'MultiVibe', url: 'https://github.com/thibautrey/multivibe/issues'}],
    name: 'multivibe-host', run_as_context: [{uid: 0, gid: 0, user_name: 'root', group_name: 'root', description: 'Entrypoint prepares dedicated mounts, then runs as UID/GID 10001 with no capabilities.'}],
    screenshots: [], sources: ['https://github.com/thibautrey/multivibe'], title: 'MultiVibe Host', train: 'community', version: '1.0.0',
  };
  files.set('truenas/multivibe-host/app.yaml', JSON.stringify(app, null, 2) + '\n');
  files.set('truenas/multivibe-host/item.yaml', JSON.stringify({categories: ['ai'], icon_url: icon, screenshots: [], tags: ['ai', 'llm', 'nvidia']}, null, 2) + '\n');
  for (const [name, contents] of files) {
    const destination = path.join(output, name);
    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, contents);
  }
  return [...files.keys()];
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const [metadataPath, sumsPath, destination] = process.argv.slice(2);
  if (!metadataPath || !sumsPath || !destination) throw new Error('Usage: generate.mjs container-release.json SHA256SUMS output-directory');
  console.log((await generate(JSON.parse(await readFile(metadataPath, 'utf8')), await readFile(sumsPath, 'utf8'), path.resolve(destination))).join('\n'));
}
