import AVFoundation
import Speech
import Observation

/// Tracks this controller's active use of the shared audio session. Releasing an
/// idle recorder must not deactivate speech playback (or another app's audio).
struct VoiceAudioSessionOwnership {
    enum Use: Equatable { case recording, playback }
    private(set) var use: Use?

    mutating func acquired(_ use: Use) { self.use = use }
    mutating func release(_ expected: Use, deactivate: () throws -> Void) throws {
        guard use == expected else { return }
        try deactivate()
        use = nil
    }
}

/// Ignore category-change notifications generated by our own activation. A route
/// loss or interruption never automatically resumes capture or spoken output.
enum VoiceSystemEvent: Sendable, Equatable {
    case interruptionBegan, routeLost, servicesLost, servicesReset
    static func decode(_ notification: Notification) -> Self? {
        if notification.name == AVAudioSession.mediaServicesWereLostNotification { return .servicesLost }
        if notification.name == AVAudioSession.mediaServicesWereResetNotification { return .servicesReset }
        if notification.name == AVAudioSession.interruptionNotification,
           let value = notification.userInfo?[AVAudioSessionInterruptionTypeKey] as? UInt,
           value == AVAudioSession.InterruptionType.began.rawValue { return .interruptionBegan }
        if notification.name == AVAudioSession.routeChangeNotification,
           let value = notification.userInfo?[AVAudioSessionRouteChangeReasonKey] as? UInt,
           value == AVAudioSession.RouteChangeReason.oldDeviceUnavailable.rawValue
            || value == AVAudioSession.RouteChangeReason.noSuitableRouteForCategory.rawValue { return .routeLost }
        return nil
    }
}

/// Dictation is explicit and foreground-only. The transcript stays editable;
/// only the Send action transmits it to MultiVibe.
@MainActor @Observable final class VoiceController: NSObject, AVSpeechSynthesizerDelegate {
    var transcript = ""
    var recording = false
    var speaking = false
    var error: String?
    private var engine = AVAudioEngine()
    private var synthesizer = AVSpeechSynthesizer()
    private var audioServicesAvailable = true
    private var recognition: SFSpeechRecognitionTask?
    private var request: SFSpeechAudioBufferRecognitionRequest?
    private var tapInstalled = false
    private var activation = UUID()
    private(set) var starting = false
    private var currentUtterance: AVSpeechUtterance?
    private var audioOwnership = VoiceAudioSessionOwnership()

    override init() {
        super.init()
        synthesizer.delegate = self
        NotificationCenter.default.addObserver(self, selector: #selector(audioSessionChanged(_:)),
                                               name: AVAudioSession.interruptionNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(audioSessionChanged(_:)),
                                               name: AVAudioSession.routeChangeNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(audioSessionChanged(_:)),
                                               name: AVAudioSession.mediaServicesWereLostNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(audioSessionChanged(_:)),
                                               name: AVAudioSession.mediaServicesWereResetNotification, object: nil)
    }

    @objc nonisolated private func audioSessionChanged(_ notification: Notification) {
        // Extract only Sendable values before crossing to the UI actor.
        guard let event = VoiceSystemEvent.decode(notification) else { return }
        Task { @MainActor [weak self] in self?.handleSystemEvent(event) }
    }

    func handleSystemEvent(_ event: VoiceSystemEvent) {
        if event == .servicesLost || event == .servicesReset {
            let wasActive = recording || speaking || starting
            // Invalidate permission/recognition continuations before discarding orphaned
            // objects. Do not stop/remove taps or deactivate the dead audio service.
            activation = UUID(); starting = false
            currentUtterance = nil; recording = false; speaking = false
            recognition?.cancel(); recognition = nil; request = nil
            tapInstalled = false; audioOwnership = VoiceAudioSessionOwnership()
            audioServicesAvailable = event == .servicesReset
            if event == .servicesReset {
                synthesizer.delegate = nil
                engine = AVAudioEngine()
                synthesizer = AVSpeechSynthesizer()
                synthesizer.delegate = self
                // Category/mode/activation are configured only on the next explicit action.
            }
            if wasActive {
                error = "Le service audio a été réinitialisé. Vérifiez le texte conservé avant de reprendre."
            }
            return
        }
        guard audioServicesAvailable, recording || speaking || starting else { return }
        silence()
        error = event == .routeLost
            ? "Le périphérique audio a été déconnecté. Vérifiez le texte conservé avant de reprendre."
            : "L’audio a été interrompu. Vérifiez le texte conservé avant de reprendre."
    }

    nonisolated func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didFinish utterance: AVSpeechUtterance) {
        let identity = ObjectIdentifier(utterance)
        Task { @MainActor [weak self] in self?.finishSpeaking(identity) }
    }
    nonisolated func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didCancel utterance: AVSpeechUtterance) {
        let identity = ObjectIdentifier(utterance)
        Task { @MainActor [weak self] in self?.finishSpeaking(identity) }
    }
    private func finishSpeaking(_ identity: ObjectIdentifier) {
        guard let currentUtterance, ObjectIdentifier(currentUtterance) == identity else { return }
        self.currentUtterance = nil; speaking = false
        releaseAudio(.playback)
    }

    private func releaseAudio(_ use: VoiceAudioSessionOwnership.Use) {
        try? audioOwnership.release(use) {
            try AVAudioSession.sharedInstance().setActive(false, options: .notifyOthersOnDeactivation)
        }
    }


    func start() async {
        guard audioServicesAvailable else { error = "Le service audio est indisponible pour le moment."; return }
        guard !recording, !starting else { return }
        let activation = UUID()
        self.activation = activation; starting = true; error = nil
        defer { if self.activation == activation { starting = false } }
        let speech = await withCheckedContinuation { continuation in
            // Speech invokes this callback off the main actor, including when already authorized.
            SFSpeechRecognizer.requestAuthorization { @Sendable status in
                continuation.resume(returning: status == .authorized)
            }
        }
        guard self.activation == activation, !Task.isCancelled else { return }
        guard speech else {
            error = "Autorisez la reconnaissance vocale dans Réglages pour dicter un message."; return
        }
        let microphone = await AVAudioApplication.requestRecordPermission()
        guard self.activation == activation, !Task.isCancelled else { return }
        guard microphone else { error = "Autorisez le microphone dans Réglages pour dicter un message."; return }
        guard let recognizer = SFSpeechRecognizer(locale: .current), recognizer.isAvailable else {
            error = "La dictée est indisponible pour le moment."; return
        }
        guard recognizer.supportsOnDeviceRecognition else {
            error = "La dictée sur l’appareil n’est pas disponible dans cette langue."; return
        }
        do {
            currentUtterance = nil; speaking = false
            synthesizer.stopSpeaking(at: .immediate)
            releaseAudio(.playback)
            let audio = AVAudioSession.sharedInstance()
            try audio.setCategory(.record, mode: .measurement, options: .duckOthers)
            try audio.setActive(true)
            audioOwnership.acquired(.recording)
            let request = SFSpeechAudioBufferRecognitionRequest()
            request.shouldReportPartialResults = true
            // Require on-device recognition; never fall back to Apple's servers.
            request.requiresOnDeviceRecognition = true
            self.request = request
            transcript = ""; error = nil
            let input = engine.inputNode
            Self.installRecordingTap(on: input, request: request)
            tapInstalled = true
            recognition = recognizer.recognitionTask(with: request) { @Sendable [weak self] result, failure in
                let text = result?.bestTranscription.formattedString
                let failed = failure != nil
                let finished = result?.isFinal == true || failed
                Task { @MainActor [weak self] in
                    guard let self, self.activation == activation else { return }
                    if let text { self.transcript = text }
                    if finished {
                        self.stop()
                        if failed {
                            self.error = "La dictée a été interrompue. Vérifiez le texte conservé avant de l’envoyer, ou recommencez."
                        }
                    }
                }
            }
            engine.prepare(); try engine.start(); recording = true
        } catch { stop(); self.error = error.localizedDescription }
    }
    // Construct the realtime callback outside MainActor isolation. Only the audio
    // tap appends buffers; UI state remains on MainActor.
    nonisolated private static func installRecordingTap(on input: AVAudioInputNode,
                                                       request: SFSpeechAudioBufferRecognitionRequest) {
        input.installTap(onBus: 0, bufferSize: 1024, format: input.outputFormat(forBus: 0)) { buffer, _ in
            request.append(buffer)
        }
    }

    func stop() {
        activation = UUID(); starting = false
        guard audioServicesAvailable else { recording = false; return }
        if engine.isRunning { engine.stop() }
        if tapInstalled { engine.inputNode.removeTap(onBus: 0); tapInstalled = false }
        request?.endAudio(); recognition?.cancel(); recognition = nil; request = nil
        recording = false
        releaseAudio(.recording)
    }
    func speak(_ text: String) {
        guard audioServicesAvailable else { error = "Le service audio est indisponible pour le moment."; return }
        silence()
        do {
            try AVAudioSession.sharedInstance().setCategory(.playback, mode: .spokenAudio, options: .duckOthers)
            try AVAudioSession.sharedInstance().setActive(true)
            audioOwnership.acquired(.playback)
            let utterance = AVSpeechUtterance(string: text)
            utterance.voice = AVSpeechSynthesisVoice(language: Locale.current.identifier)
            currentUtterance = utterance; speaking = true
            synthesizer.speak(utterance)
        } catch { self.error = error.localizedDescription }
    }
    func silence() {
        currentUtterance = nil; speaking = false
        guard audioServicesAvailable else { stop(); return }
        synthesizer.stopSpeaking(at: .immediate)
        stop()
        releaseAudio(.playback)
    }
}
