# Generated by scripts/distribution/generate.mjs from release SHA256SUMS.
cask "multivibe-host" do
  arch arm: "arm64", intel: "amd64"

  version "0.2.32"
  sha256 arm:   "71ba18a9c8b48f0c6fd2ad22f869e08c2d84f7f9b2b304990cae2163958dd6f2",
         intel: "f8d33359cacc03ebe5bcb32f8c5da861c73af6c18e7462f37a61472803ca1030"

  url "https://github.com/thibautrey/multivibe/releases/download/v#{version}/multivibe-host_#{version}_darwin_#{arch}.dmg"
  name "MultiVibe Host"
  desc "Local AI model host with a native menu bar and opt-in provider sharing"
  homepage "https://github.com/thibautrey/multivibe"

  auto_updates true
  app "MultiVibe Host.app"

  uninstall launchctl: ["cloud.multivibe.host", "cloud.multivibe.host.update"],
            quit:      "cloud.multivibe.host"

  caveats <<~EOS
    Launch MultiVibe Host from Applications to finish setup.
    Its built-in signed updater is enabled by default.
    Uninstall preserves application data and downloaded models.
  EOS
end
