import { writeFileSync } from "node:fs";
import { ACCESS as inference } from "../src/ai-sdk/expansion-inference/index.js";
import { ACCESS as subscriptions } from "../src/ai-sdk/expansion-subscriptions/index.js";
import { ACCESS as gateways } from "../src/ai-sdk/expansion-gateways/index.js";
import { CLOUD_PLATFORM_ACCESS } from "../src/ai-sdk/cloud-platforms.js";
import { SDK_PROVIDERS } from "../src/ai-sdk/providers.js";

// Keep the browser bundle independent of server adapters and Node dependencies.
writeFileSync(new URL("../web/src/lib/expandedProviderMetadata.ts", import.meta.url),
  "// Generated by node --import tsx scripts/sync-expanded-provider-metadata.ts.\n" +
  "export const EXPANDED_PROVIDER_ACCESS = " + JSON.stringify({ ...inference, ...subscriptions, ...gateways, ...CLOUD_PLATFORM_ACCESS }, null, 2) + ";\n" +
  "export const SDK_PROVIDER_NAMES: Record<string, string> = " + JSON.stringify(Object.fromEntries(SDK_PROVIDERS.map(p => [p.id, p.name])), null, 2) + ";\n");
